server:
  port: 9000

spring:
  thymeleaf:
    cache: false
  application:
    name: rbac
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://healthy_database:3306/seata2?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: slroot
    hikari:        #spring自带连接池
      pool-name: Retail_HikariCP
      minimum-idle: 5 #最小空闲连接数量
      idle-timeout: 180000 #空闲连接存活最大时间，默认600000（10分钟）
      maximum-pool-size: 10 #连接池最大连接数，默认是10
      auto-commit: true  #此属性控制从池返回的连接的默认自动提交行为,默认值：true
      max-lifetime: 1800000 #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      connection-timeout: 30000 #数据库连接超时时间,默认30秒，即30000
      connection-test-query: SELECT 1
  cloud:
    alibaba:
      seata:
        tx-service-group: songlingseata
#  redis:
#    host: localhost
#    lettuce:
#          pool:
#            max-active: 16   #默认是不使用连接池的，只有配置 redis.lettuce.pool下的属性的时候才可以使用到redis连接池

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: assign_id #自3.3.0开始,entity的id默认使用雪花算法+UUID

alibaba:
  cloud:
    nacos:
      config:
        contextPath: /nacos
        password: nacos
        server-addr: 127.0.0.1:8848
        username: nacos
      discovery:
        password: nacos
        server-addr: localhost:8848
        username: nacos
seata:
  enabled: true
  service:
    disable-global-transaction: false
    grouplist:
      default: 127.0.0.1:8091
    vgroup-mapping:
      songlingseata: default


